### ISSUE TITLE
Fatal error: Uncaught Exception: Umm... inbox is empty? in /home/redangel/i/wifiid/src/IndiHome.php:49

### ISSUE THREAD

**Issue by ammarfaizi2** [komeine/wifi-id#1]
![asda](https://user-images.githubusercontent.com/26004054/27824170-ae7820e4-60d5-11e7-9fe9-cdcc81a65377.png)

**Comment by komeine** [comment]
Tidak terdeteksi ada inbox di akunnya, coba lagi aja 🌊
